services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyDev\:
        resource: '../../{Command,Service}'
        exclude:
            - '../../Command/{BundleUpdate.php,BundleUpdateAll.php,BundleUpdateRequirements.php,UseLocalRepo.php,RemoveLocalRepo.php}'
        tags: ['controller.service_arguments']
